export const tweetFrCa = {
  created_at: 'Fri Jan 22 19:58:16 +0000 2021',
  id: 1352707172396920800,
  id_str: '1352707172396920837',
  full_text: '@humancoders TL;DR',
  truncated: false,
  display_text_range: [13, 18],
  entities: {
    hashtags: [],
    symbols: [],
    user_mentions: [
      {
        screen_name: 'humancoders',
        name: 'Human Coders',
        id: 492462042,
        id_str: '492462042',
        indices: [0, 12],
      },
    ],
    urls: [],
  },
  source:
    '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
  in_reply_to_status_id: 1352601919752073200,
  in_reply_to_status_id_str: '1352601919752073216',
  in_reply_to_user_id: 492462042,
  in_reply_to_user_id_str: '492462042',
  in_reply_to_screen_name: 'humancoders',
  user: {
    id: 879891577,
    id_str: '879891577',
    name: "Romain l'Ourson",
    screen_name: 'r_ourson',
    location: '',
    description: 'Maintainer of https://t.co/boZWfc29ah\n\nGraou !',
    url: 'https://t.co/boZWfc29ah',
    entities: {
      url: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [0, 23],
          },
        ],
      },
      description: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [14, 37],
          },
        ],
      },
    },
    protected: false,
    followers_count: 138,
    friends_count: 203,
    listed_count: 9,
    created_at: 'Sun Oct 14 11:13:07 +0000 2012',
    favourites_count: 127,
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    verified: false,
    statuses_count: 556,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: true,
    profile_background_color: '000000',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url:
      'http://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_image_url_https:
      'https://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_banner_url:
      'https://pbs.twimg.com/profile_banners/879891577/1417039033',
    profile_link_color: 'ABB8C2',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    translator_type: 'none',
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 1,
  favorited: false,
  retweeted: false,
  lang: 'fr-ca',
};

export const tweetFr = {
  created_at: 'Mon Nov 23 18:09:39 +0000 2020',
  id: 1330936564017401900,
  id_str: '1330936564017401857',
  full_text:
    "La cohérence absolue mène soit à une vie monacale, soit à du j'men-foutisme.\nAutant avoir des convictions et des contradictions.\nAu moins on avance. https://t.co/LlBEztRx6G",
  truncated: false,
  display_text_range: [0, 148],
  entities: {
    hashtags: [],
    symbols: [],
    user_mentions: [],
    urls: [
      {
        url: 'https://t.co/LlBEztRx6G',
        expanded_url:
          'https://twitter.com/Francois_Ruffin/status/1330874745085169665',
        display_url: 'twitter.com/Francois_Ruffi…',
        indices: [149, 172],
      },
    ],
  },
  source:
    '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 879891577,
    id_str: '879891577',
    name: "Romain l'Ourson",
    screen_name: 'r_ourson',
    location: '',
    description: 'Maintainer of https://t.co/boZWfc29ah\n\nGraou !',
    url: 'https://t.co/boZWfc29ah',
    entities: {
      url: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [0, 23],
          },
        ],
      },
      description: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [14, 37],
          },
        ],
      },
    },
    protected: false,
    followers_count: 138,
    friends_count: 203,
    listed_count: 9,
    created_at: 'Sun Oct 14 11:13:07 +0000 2012',
    favourites_count: 127,
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    verified: false,
    statuses_count: 556,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: true,
    profile_background_color: '000000',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url:
      'http://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_image_url_https:
      'https://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_banner_url:
      'https://pbs.twimg.com/profile_banners/879891577/1417039033',
    profile_link_color: 'ABB8C2',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    translator_type: 'none',
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: true,
  quoted_status_id: 1330874745085169700,
  quoted_status_id_str: '1330874745085169665',
  quoted_status_permalink: {
    url: 'https://t.co/LlBEztRx6G',
    expanded: 'https://twitter.com/Francois_Ruffin/status/1330874745085169665',
    display: 'twitter.com/Francois_Ruffi…',
  },
  quoted_status: {
    created_at: 'Mon Nov 23 14:04:00 +0000 2020',
    id: 1330874745085169700,
    id_str: '1330874745085169665',
    full_text:
      'Pourquoi mes livres sont en vente sur Amazon (et pourquoi je ne les retire pas).\n\nhttps://t.co/yQ66E0zBxi',
    truncated: false,
    display_text_range: [0, 105],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: 'https://t.co/yQ66E0zBxi',
          expanded_url: 'https://francoisruffin.fr/livres-ruffin-amazon/',
          display_url: 'francoisruffin.fr/livres-ruffin-…',
          indices: [82, 105],
        },
      ],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 801822323825410000,
      id_str: '801822323825410049',
      name: 'François Ruffin',
      screen_name: 'Francois_Ruffin',
      location: 'Amiens, France',
      description: "Ils ont l'argent, on a les gens.",
      url: 'https://t.co/VfaTIBnTNQ',
      entities: {
        url: {
          urls: [
            {
              url: 'https://t.co/VfaTIBnTNQ',
              expanded_url: 'http://francoisruffin.fr',
              display_url: 'francoisruffin.fr',
              indices: [0, 23],
            },
          ],
        },
        description: { urls: [] },
      },
      protected: false,
      followers_count: 214854,
      friends_count: 1482,
      listed_count: 891,
      created_at: 'Thu Nov 24 16:18:33 +0000 2016',
      favourites_count: 3013,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 7349,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '000000',
      profile_background_image_url:
        'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https:
        'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url:
        'http://pbs.twimg.com/profile_images/1313731672723030023/k71SoNOp_normal.jpg',
      profile_image_url_https:
        'https://pbs.twimg.com/profile_images/1313731672723030023/k71SoNOp_normal.jpg',
      profile_banner_url:
        'https://pbs.twimg.com/profile_banners/801822323825410049/1569496853',
      profile_link_color: 'E81C4F',
      profile_sidebar_border_color: '000000',
      profile_sidebar_fill_color: '000000',
      profile_text_color: '000000',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 367,
    favorite_count: 1176,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'fr',
  },
  retweet_count: 0,
  favorite_count: 0,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'fr',
};

export const tweetNull = {
  created_at: 'Fri Jan 22 19:58:16 +0000 2021',
  id: 1352707172396920800,
  id_str: '1352707172396920837',
  full_text: '@humancoders TL;DR',
  truncated: false,
  display_text_range: [13, 18],
  entities: {
    hashtags: [],
    symbols: [],
    user_mentions: [
      {
        screen_name: 'humancoders',
        name: 'Human Coders',
        id: 492462042,
        id_str: '492462042',
        indices: [0, 12],
      },
    ],
    urls: [],
  },
  source:
    '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
  in_reply_to_status_id: 1352601919752073200,
  in_reply_to_status_id_str: '1352601919752073216',
  in_reply_to_user_id: 492462042,
  in_reply_to_user_id_str: '492462042',
  in_reply_to_screen_name: 'humancoders',
  user: {
    id: 879891577,
    id_str: '879891577',
    name: "Romain l'Ourson",
    screen_name: 'r_ourson',
    location: '',
    description: 'Maintainer of https://t.co/boZWfc29ah\n\nGraou !',
    url: 'https://t.co/boZWfc29ah',
    entities: {
      url: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [0, 23],
          },
        ],
      },
      description: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [14, 37],
          },
        ],
      },
    },
    protected: false,
    followers_count: 138,
    friends_count: 203,
    listed_count: 9,
    created_at: 'Sun Oct 14 11:13:07 +0000 2012',
    favourites_count: 127,
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    verified: false,
    statuses_count: 556,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: true,
    profile_background_color: '000000',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url:
      'http://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_image_url_https:
      'https://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_banner_url:
      'https://pbs.twimg.com/profile_banners/879891577/1417039033',
    profile_link_color: 'ABB8C2',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    translator_type: 'none',
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 1,
  favorited: false,
  retweeted: false,
  lang: null,
};

export const tweetIn = {
  created_at: 'Fri Jan 22 19:58:16 +0000 2021',
  id: 1352707172396920800,
  id_str: '1352707172396920837',
  full_text: '@humancoders TL;DR',
  truncated: false,
  display_text_range: [13, 18],
  entities: {
    hashtags: [],
    symbols: [],
    user_mentions: [
      {
        screen_name: 'humancoders',
        name: 'Human Coders',
        id: 492462042,
        id_str: '492462042',
        indices: [0, 12],
      },
    ],
    urls: [],
  },
  source:
    '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
  in_reply_to_status_id: 1352601919752073200,
  in_reply_to_status_id_str: '1352601919752073216',
  in_reply_to_user_id: 492462042,
  in_reply_to_user_id_str: '492462042',
  in_reply_to_screen_name: 'humancoders',
  user: {
    id: 879891577,
    id_str: '879891577',
    name: "Romain l'Ourson",
    screen_name: 'r_ourson',
    location: '',
    description: 'Maintainer of https://t.co/boZWfc29ah\n\nGraou !',
    url: 'https://t.co/boZWfc29ah',
    entities: {
      url: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [0, 23],
          },
        ],
      },
      description: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [14, 37],
          },
        ],
      },
    },
    protected: false,
    followers_count: 138,
    friends_count: 203,
    listed_count: 9,
    created_at: 'Sun Oct 14 11:13:07 +0000 2012',
    favourites_count: 127,
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    verified: false,
    statuses_count: 556,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: true,
    profile_background_color: '000000',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url:
      'http://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_image_url_https:
      'https://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_banner_url:
      'https://pbs.twimg.com/profile_banners/879891577/1417039033',
    profile_link_color: 'ABB8C2',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    translator_type: 'none',
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 1,
  favorited: false,
  retweeted: false,
  lang: 'in',
};

export const tweetUndefined = {
  created_at: 'Fri Jan 22 19:58:16 +0000 2021',
  id: 1352707172396920800,
  id_str: '1352707172396920837',
  full_text: '@humancoders TL;DR',
  truncated: false,
  display_text_range: [13, 18],
  entities: {
    hashtags: [],
    symbols: [],
    user_mentions: [
      {
        screen_name: 'humancoders',
        name: 'Human Coders',
        id: 492462042,
        id_str: '492462042',
        indices: [0, 12],
      },
    ],
    urls: [],
  },
  source:
    '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
  in_reply_to_status_id: 1352601919752073200,
  in_reply_to_status_id_str: '1352601919752073216',
  in_reply_to_user_id: 492462042,
  in_reply_to_user_id_str: '492462042',
  in_reply_to_screen_name: 'humancoders',
  user: {
    id: 879891577,
    id_str: '879891577',
    name: "Romain l'Ourson",
    screen_name: 'r_ourson',
    location: '',
    description: 'Maintainer of https://t.co/boZWfc29ah\n\nGraou !',
    url: 'https://t.co/boZWfc29ah',
    entities: {
      url: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [0, 23],
          },
        ],
      },
      description: {
        urls: [
          {
            url: 'https://t.co/boZWfc29ah',
            expanded_url: 'http://livres-ouverts.fr',
            display_url: 'livres-ouverts.fr',
            indices: [14, 37],
          },
        ],
      },
    },
    protected: false,
    followers_count: 138,
    friends_count: 203,
    listed_count: 9,
    created_at: 'Sun Oct 14 11:13:07 +0000 2012',
    favourites_count: 127,
    utc_offset: null,
    time_zone: null,
    geo_enabled: true,
    verified: false,
    statuses_count: 556,
    lang: null,
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: true,
    profile_background_color: '000000',
    profile_background_image_url:
      'http://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_image_url_https:
      'https://abs.twimg.com/images/themes/theme1/bg.png',
    profile_background_tile: false,
    profile_image_url:
      'http://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_image_url_https:
      'https://pbs.twimg.com/profile_images/512276552243892224/G1sP6IkU_normal.jpeg',
    profile_banner_url:
      'https://pbs.twimg.com/profile_banners/879891577/1417039033',
    profile_link_color: 'ABB8C2',
    profile_sidebar_border_color: '000000',
    profile_sidebar_fill_color: '000000',
    profile_text_color: '000000',
    profile_use_background_image: false,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    translator_type: 'none',
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 1,
  favorited: false,
  retweeted: false,
  lang: undefined,
};
